runtime: nodejs20 # Use the latest supported Node.js runtime
env: standard      # Use the standard environment (scales to zero for cost savings)
service: api   # Allow frontend to have the default route
instance_class: F1 

entrypoint: npm start 

# =========================================================================
# Environment Variables for  Database Connection
# =========================================================================
secret_env_variables:
  DB_USER: projects/793165453319/secrets/pos_db_user/versions/latest
  DB_PASSWORD: projects/793165453319/secrets/pos_db_password/versions/latest

env_variables:
  DB_NAME: "POSDB"
  CLOUD_SQL_CONNECTION_NAME: "point-of-sales-476509:us-central1:possystem"

  NODE_ENV: "production"
