runtime: nodejs20 # Use the latest supported Node.js runtime
env: standard      # Use the standard environment (scales to zero for cost savings)
service: api   # Allow frontend to have the default route
instance_class: F1 

entrypoint: npm start 

# =========================================================================
# Environment Variables for Secure Database Connection
# =========================================================================
env_variables:
  DB_USER: "web-auth"
  DB_PASSWORD: "Webauth@7"
  DB_NAME: "POSDB"
  CLOUD_SQL_CONNECTION_NAME: "point-of-sales-476509:us-central1:possystem"

  # Optional: Set Node environment
  NODE_ENV: "production"
